### ISSUE TITLE
Web For All Best Practices integration

### ISSUE THREAD

**Issue by dontcallmedom** [mdn/pab#1]
W3C has plenty of how to / techniques with regard to accessibility and internationalization (e.g. https://www.w3.org/International/techniques/authoring-html.en) - what processes or incentives can we create to get them more systematically referenced from relevant MDN pages? Conversely, how can we facilitate requests for expert opinions identified by MDN editors or readers?

The first question is whether it is appropriate to link to this kind of W3C resources from individual MDN pages- I haven't found (but may have missed) the guideline with regard to linking to external resources from MDN.

One idea would be to nudge content creators to look for and link to such documents via an automatically included "best practices" section which would point toward sources of such best practices.  That would probably only work for new pages if I understand correctly the templating system.

I could also look into providing a list of relevant links for a set of HTML elements / CSS properties to help seed some of these sections there - I did similar kind of work for the [W3C cheatsheet](https://www.w3.org/2009/cheatsheet/) back in the days.

**Comment by r12a** [comment]
I just posted a PR at https://github.com/mdn/pab/pull/18 with a suggestion of how this could be done.  The links should work, so playing with it will give more of an idea of what i had in mind. I'm flexible about how to get the links on the page - this is just an idea to promote discussion.  I think it would be useful, however, to links of this kind.  I also think we should vet the content being pointed to, in order to avoid poor quality info and link stuffing.

**Comment by dontcallmedom** [comment]
@chrisdavidmills any feedback on the best way to approach this idea?

**Comment by chrisdavidmills** [comment]
@dontcallmedom This is an interesting idea, for sure. The only thing I worry about is that it will be a challenge to get the relevant links put in the right places.

The guidelines in terms of linking to external resource from MDN are pretty relaxed — in general, anything useful and appropriate is fine; we don't want to link to things containing bad practices, out of date standards or practices, etc., we'd prefer to link to internal pages that do the same job if they are available, and we favor a neutral standard-based approach if at all possible (e.g. don't reference stuff about proprietary technologies).

So, ideas about getting those links on to the page:

1. Publish a master list of best practices examples/links that we want to point people to.
2. Write a macro that will pull in a list of best practice links and place it in the "See also" section of any page it is included on. If there is no "See also" section, automatically create one to p[ut the inks under.
3. Control which links are included by including a list of keywords in a parameter in the macro call, or perhaps by including some specialist tags on the pages in question? E.g. including the keyword or tag wfa:l10n would include links to the localization best practice articles.

**Comment by r12a** [comment]
> it will be a challenge to get the relevant links put in the right places.

I can help with that for w3c i18n links.

'See also' links currently seem to point to internal pages with further reference material of the same type.  We may need a separate section for general links.  

Personally, call me biased, but i quite like the idea of a specific 'Web for All' section, since we're keen for developers to take into account the information we point to, rather than just treat it as 'look at this too if you have time to browse'. That ends up making a  statement (ie. that MDN feels that i18n and accessibility info are important), but i think that's not such a bad thing. It helps, too, that (1) these are links to validated W3C materials, and (2) the links describe tasks related to the page in question.

Btw, i should have provided links to easily view my mocked up sample pages. Here they are:
https://rawgit.com/r12a/pab/master/webforall-demos/mdn-dir.html
https://rawgit.com/r12a/pab/master/webforall-demos/mdn-lang.html
https://rawgit.com/r12a/pab/master/webforall-demos/mdn-input.html

**Comment by chrisdavidmills** [comment]
Plan filed at https://docs.google.com/document/d/1NrZjFm_lrooL3ZmczSSYO3xQa-FG15F7p4p0koAbYU8/edit#
