### ISSUE TITLE
Follow up on reviewing the current banners we show on reference pages; need to have a clearer definition of what “on standards track” means, and also generally what warrants which warnings on a page.

### ISSUE THREAD

**Issue by alispivak** [mdn/pab#5]
Action item from January 2018 PAB meeting

**Comment by chrisdavidmills** [comment]
# Banners on reference pages

See [Page or section header indicators](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Structures/Macros/Commonly-used_macros#Page_or_section_header_indicators) for some usage examples.

## Experimental
Macro - {{seecompattable}}
The feature is experimental — [read our definition](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Guidelines/Conventions_definitions#Experimental)

## Non-standard 
Macro - {{non-standard_header}}
The feature is not on a standards track. "On a standards track" generally means that it has a proper spec written somewhere, even if this is a draft in a community group. But we should probably think more about what our definition should be here.

## Deprecated
Macro - {{deprecated_header}}, with optional parameter to indicate version of Gecko deprecated in
The feature is still in some browsers, but is in the process of being removed as it has been deprecated in the standards. So don't use it in production as it could disappear at any time. See our [official definition here](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Guidelines/Conventions_definitions#Deprecated_and_obsolete).

## Obsolete
Macro - ((obsolete_header)), with optional parameter to indicate version of Gecko obsoleted in
We have pretty much stopped using this header, and the term "obsolete", as people were constantly confused over the difference between deprecated and obsolete.

## Available in web workers
Macro - {{availableinworkers}}
Exactly as it says. This should probably be handled by some kind of icon, rather than a big header (maybe something in the web compat banner that is currently being worked on?)

## Secure context
Macro - {{securecontext_header}}
Whether the feature is available in a secure context or not. Given that the web is moving towards secure everywhere, we should soon start marking things as not secure, rather than secure. Again, perhaps this could be done as part of the web compat banner project?

**Comment by chrisdavidmills** [comment]
There are all sorted of other banners, to indicate "Supported since Firefox 24", or "Supported in Firefox OS 1.0.1", but I don't think this kind of thing should be used anymore - it is more neutral without them, plus this kind of information can be gleaned from the browser compat table.

**Comment by patrickkettner** [comment]
> web compat banner that is currently being worked on?

@chrisdavidmills  links?

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills links?

It is at a really early research phase right now, so not much to share as yet. More as I have it!

**Comment by chrisdavidmills** [comment]
Closing this; I think this stuff is done (the definitions are all on MDN now), or being covered somewhere else (the web compat banner is being thought about by Florian).
