### ISSUE TITLE
"Getting started” templates for spec editors 

### ISSUE THREAD

**Issue by alispivak** [mdn/pab#65]
Follow up with MDN team on creating “getting started” templates for spec editors to help start articles matching their specs. MDN team will need help from PAB members on this. Chris will discuss and follow up.

**Comment by alispivak** [comment]
Action item from March 2018 PAB meeting

**Comment by chrisdavidmills** [comment]
@alispivak So let's start thinking about this one. IIRC, this was about making it easier to document Web specs by facilitating creation of pages with the correct structures?

We already have the structures defined in template articles athttps://developer.mozilla.org/en-US/docs/MDN/Contribute/Structures/Page_types

During the Hack on MDN event, @dontcallmedom showed us his smarts in terms of pulling WebIDL out of specs and creating BCD data structures.

In addition, we've also talked in the past (among MDN writers) about adding page templates to the CKEditor-based Edit mode on MDN, to allow you to just start with a generated page template rather than an empty page each time.

So my wishlist here would be to combine these three parts in some way, perhaps with a workflow like this:

1. Spec is identified that needs documenting
2. Some kind of data structure is generated from the spec's WebIDL that details all the pages needing creation on MDN
3. This structure can be fed into MDN to automatically create a series of page stubs in the correct structure that represent the API in questions.
4. Editor then goes into edit mode on each one and fills them in correctly. Each page is prepopulated with the correct template structure as already defined on MDN.

If this sounds correct, I can write a plan and take it to the MDN team for further comment.

**Comment by dontcallmedom** [comment]
fwiw, this sounds very much like what I had in mind (and would be happy to help with WebIDL extraction and template generation)

**Comment by chrisdavidmills** [comment]
Cool. I've written a plan at https://docs.google.com/document/d/1GYlCWSCvJrf6R1-lJwM2-0XhtFQ1cPLxa1wZHUji97M/edit#heading=h.a3y3gjit38rw, which I'll discuss with the team this week.

**Comment by chrisdavidmills** [comment]
Ok, I've now shared this with the MDN team for feedback. Sorry for the delay.

**Comment by dontcallmedom** [comment]
The W3C TAG explainer explainer might be a first starting point for this https://github.com/w3ctag/w3ctag.github.io/blob/master/explainers.md
